# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alexandresjr/Documents/PUCRS/TCC/tcc_app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alexandresjr/Documents/PUCRS/TCC/tcc_app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexandresjr/Documents/PUCRS/TCC/tcc_app/CMakeFiles /Users/alexandresjr/Documents/PUCRS/TCC/tcc_app/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alexandresjr/Documents/PUCRS/TCC/tcc_app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tcc_app

# Build rule for target.
tcc_app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tcc_app
.PHONY : tcc_app

# fast build rule for target.
tcc_app/fast:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/build
.PHONY : tcc_app/fast

ColorTracker.o: ColorTracker.cpp.o

.PHONY : ColorTracker.o

# target to build an object file
ColorTracker.cpp.o:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/ColorTracker.cpp.o
.PHONY : ColorTracker.cpp.o

ColorTracker.i: ColorTracker.cpp.i

.PHONY : ColorTracker.i

# target to preprocess a source file
ColorTracker.cpp.i:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/ColorTracker.cpp.i
.PHONY : ColorTracker.cpp.i

ColorTracker.s: ColorTracker.cpp.s

.PHONY : ColorTracker.s

# target to generate assembly for a file
ColorTracker.cpp.s:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/ColorTracker.cpp.s
.PHONY : ColorTracker.cpp.s

Object.o: Object.cpp.o

.PHONY : Object.o

# target to build an object file
Object.cpp.o:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/Object.cpp.o
.PHONY : Object.cpp.o

Object.i: Object.cpp.i

.PHONY : Object.i

# target to preprocess a source file
Object.cpp.i:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/Object.cpp.i
.PHONY : Object.cpp.i

Object.s: Object.cpp.s

.PHONY : Object.s

# target to generate assembly for a file
Object.cpp.s:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/Object.cpp.s
.PHONY : Object.cpp.s

ObjectDetector.o: ObjectDetector.cpp.o

.PHONY : ObjectDetector.o

# target to build an object file
ObjectDetector.cpp.o:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/ObjectDetector.cpp.o
.PHONY : ObjectDetector.cpp.o

ObjectDetector.i: ObjectDetector.cpp.i

.PHONY : ObjectDetector.i

# target to preprocess a source file
ObjectDetector.cpp.i:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/ObjectDetector.cpp.i
.PHONY : ObjectDetector.cpp.i

ObjectDetector.s: ObjectDetector.cpp.s

.PHONY : ObjectDetector.s

# target to generate assembly for a file
ObjectDetector.cpp.s:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/ObjectDetector.cpp.s
.PHONY : ObjectDetector.cpp.s

tcc_app.o: tcc_app.cpp.o

.PHONY : tcc_app.o

# target to build an object file
tcc_app.cpp.o:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/tcc_app.cpp.o
.PHONY : tcc_app.cpp.o

tcc_app.i: tcc_app.cpp.i

.PHONY : tcc_app.i

# target to preprocess a source file
tcc_app.cpp.i:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/tcc_app.cpp.i
.PHONY : tcc_app.cpp.i

tcc_app.s: tcc_app.cpp.s

.PHONY : tcc_app.s

# target to generate assembly for a file
tcc_app.cpp.s:
	$(MAKE) -f CMakeFiles/tcc_app.dir/build.make CMakeFiles/tcc_app.dir/tcc_app.cpp.s
.PHONY : tcc_app.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tcc_app"
	@echo "... ColorTracker.o"
	@echo "... ColorTracker.i"
	@echo "... ColorTracker.s"
	@echo "... Object.o"
	@echo "... Object.i"
	@echo "... Object.s"
	@echo "... ObjectDetector.o"
	@echo "... ObjectDetector.i"
	@echo "... ObjectDetector.s"
	@echo "... tcc_app.o"
	@echo "... tcc_app.i"
	@echo "... tcc_app.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

